name: Tests

on: [push, pull_request]

jobs:
    tests:
        name: Tests On PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}

        strategy:
            fail-fast: false
            matrix:
                php: ['7.3', '7.4', '8.0']
                experimental: [false]
                include:
                    - php: 8.0
                      analysis: true
                    - php: 8.1
                      experimental: true

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                tools: composer:v2
                coverage: xdebug
              env:
                update: true

            - name: Install PHP Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 5
                max_attempts: 5
                command: composer update --no-interaction --no-progress

            - name: Execute PHPUnit
              run: vendor/bin/phpunit --coverage-clover clover.xml

            - name: Upload coverage results to Coveralls
              if: matrix.analysis
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                composer require php-coveralls/php-coveralls -n -W
                vendor/bin/php-coveralls --coverage_clover=clover.xml -v
